version: "3"
services: 
    app: 
        buld:
            context: .
            dockerfile: Dockerfile
        container_name: template

        volumes:
            - ./:/app
        ports:
            - "5000:3000"

        depends_on:
            - mysql
        command:
            - bash
            - -c 
            - |
              /wait-for-it.sh mysql:3307 -t 20
              npm start
    mysql:
        image: mysql:8.0.17
        container_name: mysql
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "template"
            MYSQL_DATABASE: "template"
        command: 
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./database/db:/var/lib/mysql